name: ac327c3a-5264-40a2-8c6e-1e8d7c4b37ef
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - datashader
  - tensorflow
  - xarray
  - jupyter
  - hvplot
  - cartopy
  - pandas
  - iris
  - imageio
  - jinja2==3.0.2
  - dask
